version: 0.2

phases:
  install:
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  pre_build:
    commands:

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      # - python -m unittest discover tests
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation 
      # - aws s3 mb s3://coxauto-rtva
      - aws cloudformation package --template template.yml --s3-bucket coxauto-rtva --output-template template-export.yml
      - aws cloudformation deploy --template-file template-export.yml --stack-name rtva-stack --capabilities CAPABILITY_NAMED_IAM
  

artifacts:
  type: zip
  files:
    - template-export.yml
