swagger: '2.0'
info:
  description: rtva
  version: '1.0'
  title: rtva dashboard API
tags:
  - name: rtva
    description: rtva dashboard API
schemes:
  - http
  - https
paths:
  /:
    get:
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/NotDefinedSchema"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:@Account@:function:@rtva_emotion_fetcher/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"